### ISSUE TITLE
Defense against nuker

### ISSUE THREAD

**Issue by Morningtea7** [Mirroar/hivemind#63] opened 2022-07-01 00:09 UTC
Ramparts should be built on core structures (storage, terminal, lab, factory, etc.) to protect against other player's nuker. Ramparts should be built at RCL 8 and maintained at least 10M hits.

**Comment by Mirroar** [comment] 2022-07-01 12:05
This is effectively a duplicate of #15. The plan is a little different: Ramparts only get built when an incoming nuke is detected, only on buildings that are more expensive to rebuild than the cost of the ramparts (or important enough for the room's survival). Relatively cheap buildings can just be moved (if somewhat important, like extensions) or rebuilt after the nuke hits (roads, containers).

That way we don't spend energy on rampart upkeep for rooms that will never get hit with a nuke anyways.

**Closed** 2022-07-01 12:05 UTC
